// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeOccp_CggDcwqrDwdnyzksyxOuteVn8s',
    appId: '1:790369203022:web:ed9e09a756939cf420e41f',
    messagingSenderId: '790369203022',
    projectId: 'crud-app-754d3',
    authDomain: 'crud-app-754d3.firebaseapp.com',
    storageBucket: 'crud-app-754d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIRDHkT9zhzexw-U2hohyfhO9ozVWRFMY',
    appId: '1:790369203022:android:df1dfc6bd5d4aa6d20e41f',
    messagingSenderId: '790369203022',
    projectId: 'crud-app-754d3',
    storageBucket: 'crud-app-754d3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeOccp_CggDcwqrDwdnyzksyxOuteVn8s',
    appId: '1:790369203022:web:c94b9f66f39aeaa120e41f',
    messagingSenderId: '790369203022',
    projectId: 'crud-app-754d3',
    authDomain: 'crud-app-754d3.firebaseapp.com',
    storageBucket: 'crud-app-754d3.firebasestorage.app',
  );
}
